CREATE DATABASE burgers_db;
	USE burgers_db;

CREATE TABLE burgers (
	id INT NOT NULL AUTO_INCREMENT,
	burger_name VARCHAR (50) NOT NULL,
	date TIMESTAMP NOT NULL,
	devoured BOOLEAN NOT NULL DEFAULT FALSE;
	PRIMARY KEY (id)
);

SELECT * FROM burgers;

DELETE FROM burgers WHERE id = 9;